### ISSUE TITLE
How to support digit column name

### ISSUE THREAD

**Issue by muyihao** [apache/avro-rs#30]
Due to business requirements, we must use field names that start with a number. However, this violates Avro's naming conventions. Therefore, I am wondering if there is a way to work around this limitation. From an implementation perspective, would it be feasible to modify Avro's code to support field names that start with a number? If there are better solutions, please let me know.

**Comment by martin-g** [comment]
You could use a custom [RecordFieldNameValidator](https://github.com/apache/avro-rs/blob/ebda68c12771d34f5827dae0664303b760457917/avro/src/validator.rs#L190-L224)

- https://docs.rs/apache-avro/latest/apache_avro/#custom-names-validators
- https://github.com/apache/avro-rs/blob/main/avro/README.md#custom-names-validators
