### ISSUE TITLE
discuss: Commit `Cargo.lock` instead of bumping versions in `Cargo.toml`

### ISSUE THREAD

**Issue by Xuanwo** [apache/avro-rs#4]
Hi, arvo-rs always updates its dependencies to the latest versions whenever possible. This increases our maintenance burden and forces our users to use the latest version.

For example: 

- https://github.com/apache/avro-rs/pull/3
- https://github.com/apache/avro-rs/commit/da5298733d76593c58d08b0dc6f3e9ddb750541a

I propose to:

- Use the minimum version requirements that we need instead of the latest version in `Cargo.toml`.
  For example, use `serde = "1"` instead.
- Commit `Cargo.lock` (and bump it instead) to make sure our CI happy.
- Reduce dependabot check interval to weekly or monthly.
  Users of `avro-rs` can upgrade to a compatible version as needed.

---

I'm happy to submit a PR for this if it looks good.

**Comment by xxchan** [comment]
@martin-g May I ask what's your motivation to have dependabot to upgrade dependencies frequently? :eyes:

**Comment by martin-g** [comment]
> This increases our maintenance burden

As the single maintainer of the Rust SDK for the last 3 years I cannot say that the automated PRs increase the burden at all !

> * Commit `Cargo.lock` (and bump it instead) to make sure our CI happy.

It has been there since a long time: https://github.com/apache/avro-rs/commits/main/Cargo.lock


> * Reduce dependabot check interval to weekly or monthly.

I prefer to keep the update interval shorter. This way if a dependency breaks the build I can report it upstream sooner and it will be easier to bisect the reason. Waiting longer time will increase the burden !

**Comment by martin-g** [comment]
> May I ask what's your original motivation to have dependabot to upgrade dependencies frequently?

I like to keep them up-to-date.
Using old versions of your dependencies just makes your project look unmaintained.

May I ask you back: What kind of problems did you have with the up-to-date transitive dependencies of avro-rs ? Any real issues ?

**Comment by martin-g** [comment]
> I'm not asking you to change

Is @Xuanwo and @xxchan the same person ?



> One problem is to force downstream project to upgrade all the transitive dependencies. e.g., when I want to upgrade avro-rs, I not only need to audit changes of avro-rs, but also audit serde, anyhow, ... Because these transitive dependencies might be direct dependencies of my project, and I want to know what's changed to avoid surprise.

As you suggested you could use Cargo.lock to use older versions of the transitive dependencies.
By using "serde = 1" you just let Cargo to use whatever it decides if there is no Cargo.lock and the version in Cargo.lock if it is there. 
I prefer to have control over the versions.
The same is valid in the Node.js world. Without package.lock one have no idea what is going on.

**Comment by xxchan** [comment]
> Is @Xuanwo and @xxchan the same person ?

... No



> As you suggested you could use Cargo.lock to use older versions of the transitive dependencies.
> By using "serde = 1" you just let Cargo to use whatever it decides if there is no Cargo.lock and the version in Cargo.lock if it is there.
> I prefer to have control over the versions.
> The same is valid in the Node.js world. Without package.lock one have no idea what is going on.

No, you might misunderstood Cargo's dependency management mechanism, which is very different with npm.

If `A` depends on `B`, `A` and `B` both depend on `C`:
- In Cargo, there's only one copy of `C` (if sem-ver compatible).
- In npm, `A` and `B` depends on different copies of `C`  -- This makes it reasonable to have `package.lock` for a library.

**Comment by xxchan** [comment]
> I prefer to have control over the versions.

To clarify,
- If you want to control that the latest version passes build, then only updating `Cargo.lock` is enough.
- If you also want to control downstream users to only use latest minor versions, that's when you update `Cargo.toml`. (This is what I said "unusal", but not necessarily "unreasonable")

**Comment by Xuanwo** [comment]
> Is @Xuanwo and @xxchan the same person ?

No, definitely.


> By using "serde = 1" you just let Cargo to use whatever it decides if there is no Cargo.lock and the version in Cargo.lock if it is there.

As @xxchan explained, this understanding is incorrect. Using `serde = "1"` means enforcing users to use `serde = ">=1"`, whereas specifying `serde = "1.0.123"` enforces users to use `serde = ">=1.0.123"`. In either case, users won't use the version specified by `Cargo.lock`.

The version specified in `Cargo.toml` should usually be the minimum version that can build. We expect the upstream to adhere to semantic versioning: all new versions that are semver compatible should continue to build.

**Comment by martin-g** [comment]
I am still not convinced that using a newer and semver compatible version that brings bug fixes and/or new features is bad for the users. 

Pleas provide a real issue with the current way!

**Comment by martin-g** [comment]
> It's fine if you believe the current methods are ok, as you've done most of the work.

I don't want to be the dictator here!
Any other Avro committer can make the change if (s)he believes it is better than the current way!
