### ISSUE TITLE
Logical type UUID with type "fixed" do not serialize to fixed 16

### ISSUE THREAD

**Issue by Tipnos** [apache/avro-rs#53]
Avro 1.12.0 [specifies](https://avro.apache.org/docs/1.12.0/specification/#uuid) that UUID logical types annotates to either String or Fixed 16. 

The example below serialized the UUID to a String and not a Fixed 16

```rust 
#[derive(Debug, Serialize, Deserialize)]
struct Comment {
    id: Uuid,
}

impl AvroSchema for Comment {
    fn get_schema() -> Schema {
        Schema::parse_str(
            r#"{
                "type" : "record",
                "name" : "Comment",
                "fields" : [ {
                  "name" : "id",
                  "type" : {
                    "type" : "fixed",
                    "size" : 16,
                    "logicalType" : "uuid",
                    "name": "FixedUUID" // if we remove the name attribute schema parsing fail. The name attribute is not in avro 1.12.0 specification
                  }
                } ]
             }"#,
        )
        .expect("Invalid Comment Avro schema")
    }
}

let payload = Comment {
        id: "de2df598-9948-4988-b00a-a41c0e287398".parse().unwrap(),
};
let mut buffer = Vec::new();
SpecificSingleObjectWriter::<Comment>::with_capacity(10)
    .unwrap()
    .write_ref(&payload, &mut buffer)
    .unwrap();
```

Do you plan to support it in the near future?

**Comment by martin-g** [comment]
I will try to take a look next week!
Any help is welcome! Providing a PR will make sure it is supported in nearest future! ;-)

**Comment by martin-g** [comment]
Added the test case to the suite - https://github.com/apache/avro-rs/pull/55
It works just fine locally.
I guess it has been fixed with https://github.com/apache/avro-rs/pull/9

**Comment by Tipnos** [comment]
I had a look a the test you're added, it checks that it serializes successfully but doesn't check the payload content/size to validate that uuid is encoded as 16 bytes.

I just hex dump the content of your test, the payload length is 47 bytes instead of 26.

Why 26:
- 2 bytes of Avro marker
- 8 bytes of schema fingerprint
- 16 bytes for the uuid

In the actual 47 bytes, the UUID takes 37 bytes which is its number of characters.

**Comment by martin-g** [comment]
This deserves a new issue.
The bug here is that `AvroSchema` derived Schema does not support logical types at all at the moment ...
