### ISSUE TITLE
Ability to write to Avro Object Container format

### ISSUE THREAD

**Issue by PLeVasseur** [apache/avro-rs#73]
Hello again 👋  I'm still a newbie to Apache Avro, so apologies again for the basic question. 😅 

I wanted to make sure that avro-rs can write to the [Apache Avro Object Container File](https://avro.apache.org/docs/1.12.0/specification/#object-container-files) format.

I see this capability in the Java implementation under the [DataFileWriter](https://avro.apache.org/docs/1.12.0/api/java/org/apache/avro/file/DataFileWriter.html).

Is the right place to look for the equivalent in avro-rs in the [Writer](https://docs.rs/apache-avro/0.17.0/apache_avro/struct.Writer.html) struct? It seems to support the same sorts of capabilities of using schemas.

**Comment by martin-g** [comment]
See #53

**Comment by PLeVasseur** [comment]
Thanks @martin-g -- read through the issue a bit. Seems to be fairly specific.

To the broader question of does avro-rs support support writing to files the Apache Avro Object Container File format, is the answer "yes, but there's some limitations, among them what's outlined in #53"?

Again, sorry for the newbie questions.

**Comment by martin-g** [comment]
Sorry, I was on my mobile.
I pointed you to it because it has a sample code.
It is supported via SpecificSingleObjectWriter

**Comment by PLeVasseur** [comment]
Thanks! And to double-confirm, what I posted above is also an example of how to write with a schema to the Object Container File format?

> For example [this](https://github.com/apache/avro-rs/blob/2672bd6e3827ed323698e4069c63c3d097e53ae5/avro/examples/generate_interop_data.rs#L100) looks like it'd be an example of how to use a schema and write to the [Object Container File](https://avro.apache.org/docs/1.12.0/specification/#object-container-files) format.

```rust
let mut writer = Writer::with_codec(&schema, BufWriter::new(output_file), codec);
```

**Comment by PLeVasseur** [comment]
Read over the code and examples a bit more. Based on what I've read in the examples it appears that the simple answer is: "yes!"

Closing as resolved
