### ISSUE TITLE
[feature request] Expose Python interface

### ISSUE THREAD

**Issue by kevinjqliu** [apache/avro-rs#8]
Hello! I've recently found this project. I want to chime in on a use case for the [PyIceberg](https://github.com/apache/iceberg-python) project. 

The project needs to read avro files into records. Its currently building its own cpython extension to work to use as an avro decode. 
https://github.com/apache/iceberg-python/blob/e5a58b34dd830c6ffea11649613b693f70f7cbb4/build-module.py#L44-L52

And sometimes it doesn't work reliably ([apache/iceberg-python#1093](https://github.com/apache/iceberg-python/issues/1093))

It would be great to expose a python interface via this project to read avro files.

**Comment by martin-g** [comment]
Have you tried the Avro Python SDK ?

https://avro.apache.org/docs/++version++/api/py/html/

https://pypi.org/project/avro/

**Comment by kevinjqliu** [comment]
I have not. Thanks for the pointer, I'll take a look. There's also a performance angle; the rust-based python binding might be faster.

**Comment by martin-g** [comment]
Well, if you care about performance you should not use Python in first place.
I'd be happy to accept a Pull Request with Python bindings but I personally have no interest in implementing it myself!

I'll close this issue for now but feel free to comment more!
